### ISSUE TITLE
A new paper about "Dynamic Network Embedding"

### ISSUE THREAD

**Issue by houchengbin** [Cantoria/dynamic-graph-papers#1]
Hi Yinghan and Xuhui,

We have recently published a paper about "Dynamic Network Embedding". I was wondering if you could include our paper in this repository. Further information of our work can be found at https://github.com/houchengbin/GloDyNE or https://ieeexplore.ieee.org/document/9302718.

Many thanks and best wishes,
Chengbin

**Comment by Cantoria** [comment]
Hi houchengbin,
Your issue is received. We will carefully consider your work.
